# 3NF

In [3]:
#3NF
import pandas as pd
data = {
    'Student_ID' : [1,2,3,4],
    'Student_Name' : ['Alice','Bob','Charlie','David'],
    'Course' : ['Math','Physics','Math','Chemistry'],
    'Professor':['Dr.Smith','Dr.Jhonson','Dr.Smith','Dr.Davis'],
    'Credit_Hours' : [3,4,3,5],
    'Room_Number' : [101,203,101,305]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

#create student dataFrame
student_df = df[['Student_ID','Student_Name']].drop_duplicates().reset_index(drop=True)
print("\n")
print(student_df)

courses_df = df[['Course','Credit_Hours']].drop_duplicates().reset_index(drop=True)
print("\n")
print(courses_df)

professor_df = df[['Professor','Room_Number']].drop_duplicates().reset_index(drop=True)
print("\n")
print(professor_df)

student_course_df = df[['Student_ID','Course']].drop_duplicates().reset_index(drop=True)
print("\n")
print(student_course_df)

Original DataFrame:
   Student_ID Student_Name     Course   Professor  Credit_Hours  Room_Number
0           1        Alice       Math    Dr.Smith             3          101
1           2          Bob    Physics  Dr.Jhonson             4          203
2           3      Charlie       Math    Dr.Smith             3          101
3           4        David  Chemistry    Dr.Davis             5          305


   Student_ID Student_Name
0           1        Alice
1           2          Bob
2           3      Charlie
3           4        David


      Course  Credit_Hours
0       Math             3
1    Physics             4
2  Chemistry             5


    Professor  Room_Number
0    Dr.Smith          101
1  Dr.Jhonson          203
2    Dr.Davis          305


   Student_ID     Course
0           1       Math
1           2    Physics
2           3       Math
3           4  Chemistry

In [2]:
#3NF
import pandas as pd

# Original DataFrame
data = {
    'Student_Id' : ['1DT15ENG01','1DT15ENG02','1DT15ENG03','1DT15ENG04'],
    'Student_Name' : ['Alex','Barry','Clair','David'],
    'Subject_Id' : ['15CS11','15CS13','15CS12','15CS13'],
    'Subject' : ['SQL','JAVA','C++','JAVA'],
    'Address' : ['Goa','Bengaluru','Delhi','Kochi']
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# Splitting into Student_Info
student_info = df[['Student_Id', 'Student_Name', 'Address']].drop_duplicates().reset_index(drop=True)

# Splitting into Subject_Info
subject_info = df[['Subject_Id', 'Subject']].drop_duplicates().reset_index(drop=True)

# Creating Student_Subject relation table
student_subject = df[['Student_Id', 'Subject_Id']]

# Print the resulting DataFrames
print("\nStudent_Info:")
print(student_info)
print("\nSubject_Info:")
print(subject_info)
print("\nStudent_Subject:")
print(student_subject)

Original DataFrame:
   Student_Id Student_Name Subject_Id Subject    Address
0  1DT15ENG01         Alex     15CS11     SQL        Goa
1  1DT15ENG02        Barry     15CS13    JAVA  Bengaluru
2  1DT15ENG03        Clair     15CS12     C++      Delhi
3  1DT15ENG04        David     15CS13    JAVA      Kochi

Student_Info:
   Student_Id Student_Name    Address
0  1DT15ENG01         Alex        Goa
1  1DT15ENG02        Barry  Bengaluru
2  1DT15ENG03        Clair      Delhi
3  1DT15ENG04        David      Kochi

Subject_Info:
  Subject_Id Subject
0     15CS11     SQL
1     15CS13    JAVA
2     15CS12     C++

Student_Subject:
   Student_Id Subject_Id
0  1DT15ENG01     15CS11
1  1DT15ENG02     15CS13
2  1DT15ENG03     15CS12
3  1DT15ENG04     15CS13

# BCNF

In [4]:
#BCNF
import pandas as pd

data = {
    'Emp_Id': [1, 2, 3, 4, 5],
    'Emp_Name': ['Alex', 'Bob', 'Charlie', 'David', 'Eva'],
    'Proj_Id': [101, 102, 101, 103, 102],
    'Proj_Name': ['ProjectA', 'ProjectB', 'ProjectA', 'ProjectC', 'ProjectB'],
    'Dept_Id': [201, 202, 201, 203, 202],
    'Dept_Name': ['HR', 'IT', 'HR', 'Finance', 'IT'],
    'Manager_Id': [3, 2, 3, 4, 2],
    'Manager_Name': ['Charlie', 'Bob', 'Charlie', 'David', 'Bob']
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# Emp_Info
emp_info = df[['Emp_Id', 'Emp_Name', 'Proj_Id', 'Dept_Id', 'Manager_Id']].drop_duplicates().reset_index(drop=True)

# Proj_Info
proj_info = df[['Proj_Id', 'Proj_Name']].drop_duplicates().reset_index(drop=True)

# Dept_Info
dept_info = df[['Dept_Id', 'Dept_Name']].drop_duplicates().reset_index(drop=True)

# Manager_Info
manager_info = df[['Manager_Id', 'Manager_Name']].drop_duplicates().reset_index(drop=True)

print("\nEmp_Info:")
print(emp_info)
print("\nProj_Info:")
print(proj_info)
print("\nDept_Info:")
print(dept_info)
print("\nManager_Info:")
print(manager_info)

Original DataFrame:
   Emp_Id Emp_Name  Proj_Id Proj_Name  Dept_Id Dept_Name  Manager_Id  \
0       1     Alex      101  ProjectA      201        HR           3
1       2      Bob      102  ProjectB      202        IT           2
2       3  Charlie      101  ProjectA      201        HR           3
3       4    David      103  ProjectC      203   Finance           4
4       5      Eva      102  ProjectB      202        IT           2

  Manager_Name
0      Charlie
1          Bob
2      Charlie
3        David
4          Bob

Emp_Info:
   Emp_Id Emp_Name  Proj_Id  Dept_Id  Manager_Id
0       1     Alex      101      201           3
1       2      Bob      102      202           2
2       3  Charlie      101      201           3
3       4    David      103      203           4
4       5      Eva      102      202           2

Proj_Info:
   Proj_Id Proj_Name
0      101  ProjectA
1      102  ProjectB
2      103  ProjectC

Dept_Info:
   Dept_Id Dept_Name
0      201        HR
1      202        IT
2      203   Finance

Manager_Info:
   Manager_Id Manager_Name
0           3      Charlie
1           2          Bob
2           4        David

# 4NF

In [5]:
#4NF
import pandas as pd
data = {
    'Professor_ID' : [1,2,3],
    'Professor_Name':['Dr.Smith','Dr.Jhonson','Dr.Davis'],
    'Course_ID' : [101,102,103],
    'Course_Name' : ['Math','Physics','Chemistry'],
    'Textbook_ID' : [201,202,203],
    'Textbook_Title' : ['Mathematics : A guide' , 'Physics for engineer' , 'Chemistry fundamentals'],
    'Topic_ID' : [301,302,303],
    'Topic_Name' : ['Algebra','Newtonian mechanics','chemical reactions']
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

dept_info = df[['Textbook_Title', 'Topic_ID','Topic_Name']].drop_duplicates().reset_index(drop=True)

dept_info = df[['Professor_ID', 'Professor_Name']].drop_duplicates().reset_index(drop=True)

dept_info = df[['Textbook_ID', 'Textbook_Title']].drop_duplicates().reset_index(drop=True)

dept_info = df[['Course_ID', 'Course_Name']].drop_duplicates().reset_index(drop=True)

dept_info = df[['Textbook_ID','Topic_ID','Topic_Name']].drop_duplicates().reset_index(drop=True)

Original DataFrame:
   Professor_ID Professor_Name  Course_ID Course_Name  Textbook_ID  \
0             1       Dr.Smith        101        Math          201
1             2     Dr.Jhonson        102     Physics          202
2             3       Dr.Davis        103   Chemistry          203

           Textbook_Title  Topic_ID           Topic_Name
0   Mathematics : A guide       301              Algebra
1    Physics for engineer       302  Newtonian mechanics
2  Chemistry fundamentals       303   chemical reactions

In [6]:
#4NF
import pandas as pd
data = {
    'Component_ID' : [1,2,3,4,5],
    'Component_Name' : ['Resistor','Transistor','Capacitor','IC Chip',''],
    'Supplier_ID' : [101,102,103,104,105],
    'Supplier_Name' : ['Electro_Supply','TransTech','capCorp','IC solution','Ak Memory'],
    'Plant_ID' : [201,202,203,204,205],
    'Plant_Location' : ['FactoryA','FactoryB','FactoryC','FactoryD','FactoryE'],
    'Production_ID' : [301,302,303,304,305],
    'Production_Date' : ['2022-01-10','2022-02-05','2022-03-20','2022-01-15','2022-09-06'],
    'Quality_control_ID' : [401,402,403,404,405],
    'Quality_CIntrol_Result' : ['pass','fail','pass','pass','fail']
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# Component DF
component_df = df[['Component_ID', 'Component_Name']].drop_duplicates().reset_index(drop=True)

# Production run dataframe
production_df = df[['Production_ID', 'Production_Date']].drop_duplicates().reset_index(drop=True)

# Supplier dataFrame
supplier_df = df[['Supplier_ID', 'Supplier_Name']].drop_duplicates().reset_index(drop=True)


# Quality control dataFrame
quality_control_df = df[['Quality_control_ID', 'Quality_CIntrol_Result']].drop_duplicates().reset_index(drop=True)

# plant dataFrame
plant_df = df[['Plant_ID', 'Plant_Location']].drop_duplicates().reset_index(drop=True)

# component dataFrame
component_supplier_df = df[['Component_ID','Supplier_ID','Plant_ID', 'Production_ID','Quality_control_ID']].drop_duplicates().reset_index(drop=True)

print("\component_df:")
print(component_df)
print("\nProduction run dataframe:")
print(production_df)
print("\nSupplier dataFrame:")
print(supplier_df)
print("\nQuality control dataFrame")
print(quality_control_df)
print("\nplant dataFrame")
print(plant_df)
print("\ncomponent dataFrame")
print(component_supplier_df)

Original DataFrame:
   Component_ID Component_Name  Supplier_ID   Supplier_Name  Plant_ID  \
0             1       Resistor          101  Electro_Supply       201
1             2     Transistor          102       TransTech       202
2             3      Capacitor          103         capCorp       203
3             4        IC Chip          104     IC solution       204
4             5                         105       Ak Memory       205

  Plant_Location  Production_ID Production_Date  Quality_control_ID  \
0       FactoryA            301      2022-01-10                 401
1       FactoryB            302      2022-02-05                 402
2       FactoryC            303      2022-03-20                 403
3       FactoryD            304      2022-01-15                 404
4       FactoryE            305      2022-09-06                 405

  Quality_CIntrol_Result
0                   pass
1                   fail
2                   pass
3                   pass
4                   fail
\component_df:
   Component_ID Component_Name
0             1       Resistor
1             2     Transistor
2             3      Capacitor
3             4        IC Chip
4             5

Production run dataframe:
   Production_ID Production_Date
0            301      2022-01-10
1            302      2022-02-05
2            303      2022-03-20
3            304      2022-01-15
4            305      2022-09-06

Supplier dataFrame:
   Supplier_ID   Supplier_Name
0          101  Electro_Supply
1          102       TransTech
2          103         capCorp
3          104     IC solution
4          105       Ak Memory

Quality control dataFrame
   Quality_control_ID Quality_CIntrol_Result
0                 401                   pass
1                 402                   fail
2                 403                   pass
3                 404                   pass
4                 405                   fail

plant dataFrame
   Plant_ID Plant_Location
0       201       FactoryA
1       202       FactoryB
2       203       FactoryC
3       204       FactoryD
4       205       FactoryE

component dataFrame
   Component_ID  Supplier_ID  Plant_ID  Production_ID  Quality_control_ID
0             1          101       201            301                 401
1             2          102       202            302                 402
2             3          103       203            303                 403
3             4          104       204            304                 404
4             5          105       205            305                 405